// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptimalAccessibility.API;

#nullable disable

namespace OptimalAccessibility.API.Migrations
{
    [DbContext(typeof(OptimalAccessibilityContext))]
    [Migration("20220801034801_CREATEINIT")]
    partial class CREATEINIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.Poster", b =>
                {
                    b.Property<Guid>("posterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PosterImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("Data");

                    b.Property<string>("PosterImageTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<string>("PosterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<Guid?>("accessibilityScoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("posterId");

                    b.ToTable("Posters");
                });

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.PosterAccessibilityScore", b =>
                {
                    b.Property<Guid>("accessibilityScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ColorRating")
                        .HasColumnType("integer")
                        .HasColumnName("Color");

                    b.Property<int>("StructureRating")
                        .HasColumnType("integer")
                        .HasColumnName("Structure");

                    b.Property<int>("TextRating")
                        .HasColumnType("integer")
                        .HasColumnName("Text");

                    b.Property<Guid>("posterId")
                        .HasColumnType("uuid");

                    b.HasKey("accessibilityScoreId");

                    b.ToTable("PosterAccessiblityScore");
                });

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Classfication")
                        .HasColumnType("integer");

                    b.Property<string>("EUID")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char?>("MiddleInitial")
                        .HasColumnType("character(1)");

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.UserAccessibilityScore", b =>
                {
                    b.Property<Guid>("accessibilityScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ColorRating")
                        .HasColumnType("integer")
                        .HasColumnName("Color");

                    b.Property<int>("StructureRating")
                        .HasColumnType("integer")
                        .HasColumnName("Structure");

                    b.Property<int>("TextRating")
                        .HasColumnType("integer")
                        .HasColumnName("Text");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("accessibilityScoreId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("UserAccessiblityScore");
                });

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.UserAccessibilityScore", b =>
                {
                    b.HasOne("OptimalAccessibility.Domain.Models.Database.User", null)
                        .WithOne("accessibilityScore")
                        .HasForeignKey("OptimalAccessibility.Domain.Models.Database.UserAccessibilityScore", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptimalAccessibility.Domain.Models.Database.User", b =>
                {
                    b.Navigation("accessibilityScore");
                });
#pragma warning restore 612, 618
        }
    }
}
